using System.Threading;
using System.Threading.Tasks;
using MegaEngineeringSuite.Infrastructure.Logging;

namespace MegaEngineeringSuite.TubeSheet
{
    public class ExistingGeometryGenerator : IGeometryGenerator
    {
        public Task GenerateGeometryAsync(TubeSheetData data, CancellationToken cancellationToken)
        {
            SimpleLogger.Log("ExistingGeometryGenerator", "Geometry generation bypassed. Assuming already generated by legacy script.");
            return Task.CompletedTask;
        }
    }
}
