using System;
using System.Threading;
using System.Threading.Tasks;
using MegaEngineeringSuite.Infrastructure.Cad;
using MegaEngineeringSuite.Infrastructure.Logging;

namespace MegaEngineeringSuite.TubeSheet
{
    public class PipelineOrchestrator
    {
        public async Task<bool> RunV2PipelineAsync(DrawingAutomationResult result, TubeSheetData data, DrawingInformation info)
        {
            SimpleLogger.Log("PipelineOrchestrator", "Starting V2 Pipeline Orchestration.");

            if (result.CadApplication == null || result.CadDocument == null)
            {
                SimpleLogger.Log("PipelineOrchestrator", "Error: CAD COM objects not passed from legacy service.");
                return false;
            }

            // Create adapter and attach to existing session to prevent duplicate COM instances
            var cadAdapter = new GstarCadAdapter();
            cadAdapter.AttachToExistingSession(result.CadApplication, result.CadDocument);

            var syncProvider = new CadUserVariableSynchronizationProvider(cadAdapter, "USERI1");
            var geometryGenerator = new ExistingGeometryGenerator();

            var pipeline = new TubeSheetDrawingPipeline(cadAdapter, geometryGenerator, null!, syncProvider);

            // Create context with 60s timeout
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(60));
            var context = new PipelineContext(cadAdapter, syncProvider, cts.Token)
            {
                Data = data,
                Info = info,
                WorkingDrawingPath = result.Arguments, // This holds the outDwgPath
                WorkingCopyPrepared = true,            // Already copied by DrawingAutomationService
                GeometryAlreadyGenerated = true        // Already generated by LISP
            };

            try
            {
                SimpleLogger.Log("PipelineOrchestrator", "Executing TubeSheetDrawingPipeline...");
                await pipeline.ExecuteAsync(context);
                SimpleLogger.Log("PipelineOrchestrator", "Pipeline executed successfully.");
                RuntimeTraceLogger.DumpTrace();
                return true;
            }
            catch (OperationCanceledException)
            {
                SimpleLogger.Log("PipelineOrchestrator", "Timeout Error: LISP execution exceeded 60 seconds without completing.");
                Rollback(context);
                RuntimeTraceLogger.DumpTrace();
                return false;
            }
            catch (Exception ex)
            {
                SimpleLogger.Log("PipelineOrchestrator", $"Error: Pipeline execution failed - {ex.Message}");
                RuntimeTraceLogger.Log("\n### Pipeline Exception Trapped");
                RuntimeTraceLogger.Log($"Exception Type: {ex.GetType().Name}");
                RuntimeTraceLogger.Log($"Message: {ex.Message}");
                RuntimeTraceLogger.Log($"Phase: {context.CurrentPhase}");
                RuntimeTraceLogger.Log($"Stack Trace:\n{ex.StackTrace}");
                if (ex.InnerException != null)
                {
                    RuntimeTraceLogger.Log($"Inner Exception: {ex.InnerException.Message}");
                }
                
                Rollback(context);
                RuntimeTraceLogger.DumpTrace();
                return false;
            }
        }

        private void Rollback(PipelineContext context)
        {
            try
            {
                SimpleLogger.Log("PipelineOrchestrator", "Initiating rollback. Closing active document without saving.");
                
                RuntimeTraceLogger.Log("\n### Rollback Triggered");
                RuntimeTraceLogger.Log($"Rollback invoked because:");
                RuntimeTraceLogger.Log($"Exception: {context.LastException?.Message ?? "Timeout / Unknown"}");
                RuntimeTraceLogger.Log($"Pipeline phase: {context.CurrentPhase}");
                RuntimeTraceLogger.Log($"Current placeholder count: {context.PlaceholderIndex.Count}");
                RuntimeTraceLogger.Log($"Replacement count: (N/A at orchestration level)");
                RuntimeTraceLogger.Log($"Document modified: Unknown (COM restricted)");
                RuntimeTraceLogger.Log($"Document name: {context.WorkingDrawingPath}");
                
                context.CadAdapter.CloseDrawing(); // Closes the document, does not quit application
            }
            catch (Exception ex)
            {
                SimpleLogger.Log("PipelineOrchestrator", $"Rollback failed: {ex.Message}");
            }
        }
    }
}
