using System;

namespace MegaEngineeringSuite
{
    public static class DraftingScaleManager
    {
        // Paper Space Target Sizes (SheetLayoutEngine will convert these into model-space heights)
        // Values as per Phase 5F hierarchy requirements

        public static float GetPaperSpaceMainTitleHeight() 
        { 
            return 31.0f;
        }

        public static float GetPaperSpaceDetailTitleHeight() 
        { 
            return 31.0f;
        }

        public static float GetPaperSpaceDimensionHeight() 
        { 
            return 31.0f; // Dimensions are technically not text, but user said 'all automatically generated text' and listed PCD Ø. If dimensions don't work well, we might need to separate it, but let's see. 
            // Wait, the user said "Do not modify any geometry, dimensions, leaders, or engineering calculations."
            // But they also said "This includes: TUBE LIMIT Ø, PCD Ø". If those are dimensions, what to do?
            // Actually, in DrawingAutomationService, TUBE LIMIT Ø and PCD Ø are drawn via _.DIMLINEAR, but what about in C# preview?
        }

        public static float GetPaperSpaceStandardNotesHeight() 
        { 
            return 31.0f; 
        }

        public static float GetPaperSpaceRowCountHeight() 
        { 
            return 31.0f; 
        }

        // Keep table cell and title block fields stable if they are not considered "engineering notes"? 
        // "Specification table text" is explicitly requested! "Every text entity generated by the application must use the same drafting standard."
        public static float GetPaperSpaceSpecHeaderHeight() { return 31.0f; }
        public static float GetPaperSpaceTableCellHeight() { return 31.0f; }
        public static float GetPaperSpaceTitleBlockFieldHeight() { return 31.0f; }
        
        // These are kept for backward compatibility if any view still calls them
        public static float GetMainTitleTextHeight(float outerDiameter) { return GetPaperSpaceMainTitleHeight(); }
        public static float GetDetailTitleTextHeight(float outerDiameter) { return GetPaperSpaceDetailTitleHeight(); }
        public static float GetStandardDraftingTextHeight(float outerDiameter) { return GetPaperSpaceStandardNotesHeight(); }
        public static float GetPaperSpaceTextHeight() { return GetPaperSpaceStandardNotesHeight(); }
    }
}
